export const FETCH_AUDIT_LOGS = 'FETCH_AUDIT_LOGS;'
export const RECIEVE_AUDIT_LOGS = 'RECIEVE_AUDIT_LOGS;'

export const FETCH_STATISTICS = 'FETCH_STATISTICS';
export const RECIEVE_STATISTICS = 'RECEIVE_STATISTICS';